### ISSUE TITLE
VMWare Workstation provider fails on creating private network.

### ISSUE THREAD

**Issue by jarpy** [mitchellh/vagrant#4780]
The following Vagrantfile fails to come up with VMWare Workstation:
```
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "omalley/centos6_x64"
  config.vm.network :private_network, ip: '10.10.10.0'
end
```
To replicate:
* Ensure that no VMWare virtual network is defined for 10.10.10.0/24
* vagrant up

May be related to this debug output:
```
INFO subprocess: Starting process: ["/usr/bin/vmware-networks", "--configure"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: /usr/bin/vmware-networks: unrecognized option '--configure'
```

Full debug output in this Gist:
  https://gist.github.com/jarpy/970ff4102b96f6ba27b8

**Comment by mitchellh** [comment]
This is fixed, we now ignore if `--configure` is missing. We have to still execute it because some versions do support it.

**Comment by sethvargo** [comment]
To further elaborate - you will need to be running the newest version of the plugin or later (3.1.2+).

**Comment by uchagani** [comment]
is there a changelog of what was fixed, etc.?  I'd like to know before I
update my plugin.

**Comment by sethvargo** [comment]
@uchagani the plugin changelogs are public: https://github.com/hashicorp/vagrant-plugin-changelog

**Comment by mitchellh** [comment]
@uchagani Just wait for the next version (see the changelog, wait for the next release) to be sure.

**Comment by uchagani** [comment]
Thanks for the heads up


On Mon, Jan 5, 2015 at 5:25 PM, Mitchell Hashimoto <notifications@github.com

**Comment by jmiller0** [comment]
Confirmed this is still an issue

vagrant up --provider vmware_workstation --debug 2>&1 | egrep 'vmware-networks.+configure' | head -n2
DEBUG subprocess: stderr: INFO subprocess: Starting process: ["/usr/bin/vmware-networks", "--configure"]
DEBUG subprocess: stderr: DEBUG subprocess: stderr: /usr/bin/vmware-networks: unrecognized option '--configure'

vagrant plugin list
vagrant-share (1.1.3, system)
vagrant-vmware-workstation (3.2.4)

Can you guys test this with vmware workstation v11?

**Comment by mitchellh** [comment]
@jmiller0 We still output that but we ignore it. We just log the stderr.

**Comment by jmiller0** [comment]
So I'm not seeing any other terrors in my log. How do I debug why the adapter is not being created or coming up?

Thanks

**Comment by jmiller0** [comment]
This issue has been fixed with vagrant-vmware-workstation (3.2.5)
