### ISSUE TITLE
Allowing symlinks in shared folders using the vagrant-vmware-workstation plugin is not functioning.

### ISSUE THREAD

**Issue by aworstell** [mitchellh/vagrant#4809]
By default, creating symlinks in shared folders in VMware Workstation is disabled. To enable this, you need to add the line: 
```
sharedFolder0.followSymlinks = "TRUE"
```
where 0 is the number of the shared folder you want to enable symlinks in. 
If you set this in the .vmx file before vagrant provisions the box, it overwrites that line entirely. 
If you configure the Vagrantfile to set it in the vmx: 
```
v.vmx["sharedFolder0.followSymlinks"] = "TRUE"
```

it writes the .vmx  file as:
```
sharedfolder0.followsymlinks = "FALSE"
```
This was reported on the email list back in March:
https://groups.google.com/forum/#!topic/vagrant-up/72G0iEU1n6o

**Comment by mitchellh** [comment]
This is fixed! Another release is coming out tonight.

**Comment by create-renegr** [comment]
It does not work for me (vagrant: 1.7.2, host: win8.1).

When I up the VM, I can see ``sharedfolder0.followsymlinks = "TRUE"``.
But when the sharedfolders are being created, the contents in the vmx file changes to:
``sharedfolder0.followsymlinks = "FALSE"``

Any Ideas @mitchellh  ?


(Other from that I get an ``ENAMETOOLONG`` error, when installing npm packages. But I could not find any solutions for that either. Maybe I am lucky and you have one for this?)

**Comment by aworstell** [comment]
@create-renegr All of my research on this shows to be that using npm in shared windows just plain does not work. My workaround is to move the working folder outside of shared folder space to use npm, then move it back when done.

**Comment by create-renegr** [comment]
@aworstell  tried that and it works (npm-wise). i get a bunch of warning "cannot create symlink", but it works.

Nevertheless, it does not solve the problem why "true" changes to "false" during boot.

**Comment by etikka** [comment]
I have the same problem and OS/vagrant version as @create-renegr.

Before vagrant up
I tried to set in the vagrant file:
`v.vmx["sharedFolder0.followSymlinks"] = "TRUE"`

I also tried to manually set in the vmx:
`sharedfolder0.followsymlinks = "TRUE"`

Once the VM was up, the line in .vmx had disappeared.

It would be great if follow symlinks would be on as a default.

**Comment by pixelrebel** [comment]
I also have this same problem.  I don't know why this is closed.

**Comment by Moonlighter** [comment]
hi,

Yesterday i try to install angularjs-cli on SharFolder between a host (Windows10) and à VM on VMware 12(Workstation, with Ubuntu 14.04 LTS)

[In my Ubuntu.vmx]

sharedFolder0.present = "TRUE"
sharedFolder0.enabled = "TRUE"
sharedFolder0.readAccess = "TRUE"
sharedFolder0.writeAccess = "TRUE"
sharedFolder0.hostPath = "C:\wamp\www"
sharedFolder0.guestName = "www"
sharedFolder0.expiration = "session"
sharedFolder0.followSymlinks = "TRUE"

I access to my ShareFolder on my VM here /mnt/hgfs/www/

So after i try to install i receive this issues:

EACCES: permission denied, symlink '../semver/bin/semver' -> '/mnt/hgfs/www/ang20/my-demo/node_modules/agent-base/node_modules/.bin/semver'
Error: EACCES: permission denied, symlink '../semver/bin/semver' -> '/mnt/hgfs/www/ang20/my-demo/node_modules/agent-base/node_modules/.bin/semver'
    at Error (native)

Somebody have an idea? Thank's!
