### ISSUE TITLE
Unable to puppet provision without reloading Vagrant

### ISSUE THREAD

**Issue by bdgeorge** [mitchellh/vagrant#4810]
## Problem
I consistently get the following error when attempting to `vagrant provision` with the Puppet Librarian Plugin and VMWare fusion provider:

```
Shared folders that Puppet requires are missing on the virtual machine.
This is usually due to configuration changing after already booting the
machine. The fix is to run a `vagrant reload` so that the proper shared
folders will be prepared and mounted on the VM.
```

Provisioning only works with a `vagrant reload --provision`

Doing a `vagrant provision`, or even a `vagrant reload` followed by immediately by `vagrant provision` however results in the error.

## Speculation
While it's similar to issue #2134 I'm on vagrant 1.6.5 which should contain the fix for that.
It may to be related to using the puppet librarian vagrant plugin, the same vagrantfile but without puppet librarian works fine.

(So my suspicion is that it has something to do with the way puppet librarian deletes and recreates the modules directory each time it runs)

## System
OSX 10.10 and OSX10.9
Vagrant 1.6.5
VMWare Fusion 6 and 7
vagrant-librarian-puppet (0.7.1)
vagrant-vmware-fusion (3.1.0)

## Vagrant File
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "hashicorp/precise64"

  # Forward guest port 80 to host port 8888 and name mapping
  config.vm.network "private_network", ip: "192.168.160.3"

  # Forward the Rails server default port to the host
  config.vm.network :forwarded_port, guest: 3000, host: 3000

  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "512"
  end

  # This shell provisioner installs librarian-puppet and runs it to install
  # puppet modules. This has to be done before the puppet provisioning so that
  # the modules are available when puppet tries to parse its manifests.
  #config.vm.provision :shell, :path => "shell/main.sh"

  config.librarian_puppet.puppetfile_dir = "puppet"
  # placeholder_filename defaults to .PLACEHOLDER
  config.librarian_puppet.placeholder_filename = ".puppetkeep"

  ### Enable the Puppet provisioner, with will look in manifests
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file = "default.pp"
    puppet.module_path = ["puppet/modules"]
  end

end
```

**Comment by sethvargo** [comment]
This is fixed in Vagrant 1.7.2

**Comment by bdgeorge** [comment]
Thanks Seth - does this close #2134 as well?

**Comment by sethvargo** [comment]
@bdgeorge should be - at least it's related.

**Comment by bdgeorge** [comment]
Just upgraded to 1.7.2 and I'm still getting the same problem I'm afraid.

**Comment by fivetanley** [comment]
I hate to +1 but I'm also getting this on vagrant 1.7.2.
