### ISSUE TITLE
support long paths on windows hosts, by rebinding the share to a UNC path

### ISSUE THREAD

**Issue by Pomax** [mitchellh/vagrant#4815]
Based on https://github.com/mitchellh/vagrant/issues/1953#issuecomment-60852879 and the workaround provided in https://www.virtualbox.org/ticket/11976#comment:2, it might make sense to make vagrant do the rebindng from "plain path" to UNC path during the creation step on windows platforms.

This would allow vagrant to actually be a viable technology on windows hosts for nodejs setups (npm installs are notorious for stupidly long dependency chains, with deduplication only happening *after* the full, deep, installation of all dependencies)

**Comment by Pomax** [comment]
@sethvargo I'd mark this a bug, not an enhancement. Shared dirs are unpredictably broken so we can't rely on them on windows, whereas we can rely on them in unix/linux/osx (you can't ask whether the dir you're going to write works. If you could, this would probably more an enhancement than bug)

**Comment by sethvargo** [comment]
@Pomax I'll defer to @mitchellh on that :smile:

**Comment by Pomax** [comment]
@mitchellh if you're looking in, can you confirm you've seen this bug please? There's a fair amount of activity but no signal that you've seen this makes it seem like we're talking amongst ourselves =)

**Comment by ClementParis016** [comment]
Would be great to see this issue fixed :+1: 

In the meantime, could someone explain how to fix this temporarily while waiting an official update?

**Comment by celtric** [comment]
Can confirm that @chernetsov0 solution works on Windows 7, using Vagrant 1.7.2 and VirtualBox 4.3.20.

```diff
# Lines 495-510 - C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.2\plugins\providers\virtualbox\driver\version_4_3.rb
def share_folders(folders)
  folders.each do |folder|
    args = ["--name",
      folder[:name],
      "--hostpath",
-       folder[:hostpath]]
+      '\\\\?\\' + folder[:hostpath].gsub(/[\/\\]/,'\\')]
    args << "--transient" if folder.key?(:transient) && folder[:transient]

    # Enable symlinks on the shared folder
    execute("setextradata", @uuid, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/#{folder[:name]}", "1")

    # Add the shared folder
    execute("sharedfolder", "add", @uuid, *args)
  end
end
```

**Comment by sirlatrom** [comment]
+1

**Comment by jgoux** [comment]
Awesome @chernetsov0 and @celtric , thanks a lot for this hack !
I hope this will be added in the next release.

**Comment by nschubach** [comment]
I am not able to get this patch to work.  I modified the version_4_3.rb file as noted above and changed my synced folder to be absolute:

Vagrant file:
    Vagrant.configure(2) do |config|
        config.vm.box = "deimosfr/debian-jessie"
        config.vm.network "forwarded_port", guest: 8000, host: 8000
        config.vm.network "private_network", ip: "192.168.3.10"
        config.vm.synced_folder File.dirname(__FILE__), '/vagrant', create: true

        config.vm.provider "virtualbox" do |vb|
            vb.gui = true
            vb.memory = "1024"
        end

        config.vm.provision "shell", inline: <<-SHELL
            sudo apt-get update
            sudo apt-get install -y nodejs nodejs-legacy npm git
            cd /vagrant
            npm install gulp
        SHELL
    end

Which fails pretty hard when it gets to the gulp install.

**Comment by nicekiwi** [comment]
@nschubach did you try running with 'sudo' as the feedback recommends?

**Comment by nicekiwi** [comment]
+1

**Comment by dtfinch** [comment]
chernetsov0's fix worked in my case, with Vagrant 1.7.2 and VirtualBox 4.3.22 on Windows 7 64-bit.

**Comment by nschubach** [comment]
@nicewiki Yes, I've tried running sudo npm install and it still gives:

    ==> default: npm
    ==> default:
    ==> default: ERR!
    ==> default:   { [Error: EPERM, open '/vagrant/node_modules/gulp-ng-annotate/node_modules/gulp-util/node_modules/lodash.template/node_modules/lodash.escape
    /node_modules/lodash._reunescapedhtml/package.json']
    ==> default: npm
    ==> default:
    ==> default: ERR!
    ==> default:    errno: 50,

Vagrant 1.7.2, VirtualBox 4.1.8 (checking updates states I'm at the latest version...) and Windows 7 64-bit.  This is on an NTFS partition, on an SSD, with all users having full control over the folder where the source code is saved.

**Comment by nicekiwi** [comment]
@nschubach why did you change your sync folder to absolute? does that directory actually exist?

**Comment by nicekiwi** [comment]
chernetsov0's first code worked for me too. Didn't need to change my sync dir.

**Comment by bencomeau** [comment]
chernetsov0 and celtric's changes worked for me too. Working with Vagrant 1.7.2, VirtualBox 4.3.22, Windows 7 Pro 64

**Comment by jfbibeau** [comment]
:+1: Please add this to the next Vagrant release. Has anyone opened a PR for this yet?

**Comment by fusionstrings** [comment]
:+1:  The very point of using tools like Vagrant is to provide portable repos to developers regardless of the OS their machine is running. Infact using Vagrant has more justification for Windows users than any other platform. I myself not able to recommend Vagrant because of this issue. If this doesn't work then windows should not be in support list. That would make it easier.

Eagerly waiting for some fixes.

**Comment by Ingramz** [comment]
I am unable to produce a PR right now but I'm submitting my version of the path name here.

so instead of
```rb
folder[:hostpath]
```

I'm offering this line:
```ruby
Vagrant::Util::Platform.windows? ? ("//?/" + File.expand_path(folder[:hostpath])).gsub("/","\\") : folder[:hostpath]
```

This way anyone using not windows will have the same experience and for windows paths relative ones are converted to absolute as relative paths are not supported in the UNC format. I do not know if there are any caveats to converting the path beforehand, so I'd like to hear your feedback.

You might also notice that I'm not a ruby programmer.

**Comment by BenLiyanage** [comment]
This worked for me, though performance seems to have tanked on the share now.

**Comment by drmyersii** [comment]
I've spent about 16 hours working on this today (I wish I was exaggerating), and I finally have a solution to the Vagrant/Windows issue at hand. I have been working on a Node.js development environment built on Vagrant, and I have been relentlessly determined to get this working. 

[This is the commit that I implemented it in](https://github.com/renobit/vagrant-node-env/commit/bdf15f2f301e2b1660b839875e34f172ea8be227), but I'll go ahead and post the main snippet of code here:

```ruby
config.vm.provider "virtualbox" do |v|
    v.customize ["sharedfolder", "add", :id, "--name", "www", "--hostpath", (("//?/" + File.dirname(__FILE__) + "/www").gsub("/","\\"))]
end

config.vm.provision :shell, inline: "mkdir /home/vagrant/www"
config.vm.provision :shell, inline: "mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` www /home/vagrant/www", run: "always"
```

In the code above, I am appending ```\\?\``` to the current directory absolute path. This will actually force the Windows API to allow an increase in the MAX_PATH variable (normally capped at 260). Read more about [max path](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#maxpath). This is happening during the sharedfolder creation which is intentionally handled by VBoxManage and not Vagrant's "synced_folder" method. The last bit is pretty self-explanatory; we create the new shared folder and then make sure it's mounted each time the machine is accessed or touched since Vagrant likes to reload its mounts/shared folders on each load.

I absolutely hope this helps everyone that was struggling with this like I was!

**Comment by jfbibeau** [comment]
Created pull request #5495 to make it easier to get a fix in for this issue.

**Comment by iget-master** [comment]
There's any forecast for this fix release? This is an important bug!

**Comment by bodhisatttwa** [comment]
I struggled with this on win 10 + virtualbox 5.0 + vagrant 1.7.4, however I then installed the gulp + laravel-elixir globally (npm install --global) instead of in the app folder which cause problems because it's mapped to win dir, gulp command now works fine in the app context

**Comment by ezequieltejada** [comment]
On Windows 10, VirtualBox 5.0.1, and Vagrant 1.7.4

Once I made the change suggested by @celtric in C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.4\plugins\providers\virtualbox\driver\version_5_0.rb (line 511) I get the following error.

![capture](https://cloud.githubusercontent.com/assets/4989765/9563633/2ad67878-4e60-11e5-9d40-bee921c71593.PNG)

Once I revert the change I still get the original error:

![capture](https://cloud.githubusercontent.com/assets/4989765/9563639/647bea5e-4e60-11e5-9a16-122b733010a8.PNG)

I'll try installing the packages using the "--global" parameter.

**Comment by Pomax** [comment]
**Please understand that activity in closed issues is likely to be entirely ignored**

Tempting as it is, don't keep commenting on this issue: it was for UNC support in pre-1.7.3, and we've passed that point. 1.7.4 is out, and if you are having problems with 1.7.4, **file a new issue about that** so that we can all discuss the problems you are having with it in the right place.

**do not comment on this thread anymore, this issue was correctly resolved through 1.7.3. If you have problems with 1.7.3, or 1.7.4, file a new issue, or comment on an already existing one. Not here**

**Comment by morokolo** [comment]
This is how we get the magic in our pants :

1. Using your windows explorer,Navigate to your vagrant shared folder (I am using scotchbox by the way) e.g C:\scotchbox/public/gulpProject
2. in the address bar of the folder, type cmd and press enter
3. do your gulp installation npm install anything you want bitches...oh what is that ? No errors
4. Do the suck my duck dance!!!

**Comment by dantheman213** [comment]
Hey guys, I created a script to fix this issue. My solution was to execute the project in a part of the VM that wasn't being shared with Windows. The script can be run over and over again to run a project. It copies the base project to a temporary execution directory. If you're running it 2nd time + it checks for file differences and will run npm install if your "package.json" file has changed. Lastly it runs npm install inside the execution directory and voila! Workaround complete. :)

Check it out here guys:
https://gist.github.com/dantheman213/7a505004d26c480e8274

**Comment by berpcor** [comment]
Hello. I have the latest version of Vagrant, but the problem is still exists.
I have npm EACCES error. Too long file names for Windows.
Is there any patch?
Should I manually make corrections like said[above](https://github.com/mitchellh/vagrant/issues/4815#issuecomment-74040523)?

**Comment by Ingramz** [comment]
@berpcor there would be no point because it has been already added to the latest version of Vagrant.

There are a couple of ways you can work around your issues and they are all mentioned in the PR starting from post https://github.com/mitchellh/vagrant/pull/6493#issuecomment-187139779

**Comment by berpcor** [comment]
My bad. I have already not the latest version of Vagrant. I read here that the latest version of Virtualbox can solve the problem. Reinstalled it, but my Vagrant stopped working. Now, when you said about version, I checked mine... Need to install it...

**Comment by morokolo** [comment]
Open your project folder, I am using scothbox eg C:/scothbox/public/mywebapp

in the address bar, ctrl+a if not all selected then type cmd

from there do your npm install

**Comment by berpcor** [comment]
I've installed the last version of Vagrant and Virtualbox. Problem is still exists...

**Comment by Ingramz** [comment]
@berpcor read the workarounds I mentioned earlier. Try `npm install --no-bin-links` first and if that fails, you'll need to explain exactly what's the problem you are having.

**Comment by dantheman213** [comment]
I just make sure "node_modules/" is removed from my Node.JS project then 
I create that folder at /root or somewhere else in my Vagrant that is 
not shareable. I think create a symlink from 
/home/user/myproject/node_modules to /root/node_modules and then run 
"npm install" inside my project directory. This makes everything work great!
