### ISSUE TITLE
Vagrant lost it's association with existing boxes after upgrading to 1.7.1

### ISSUE THREAD

**Issue by bdgeorge** [mitchellh/vagrant#5105]
There seem to be a number of similar issues with older vagrant releases (eg #1755), but I've found that after upgrading vagrant to 1.7.1 many vagrant projects have lost their associated boxes.

I'm mainly running VMware fusion, and this seems to apply only to projects using the Virtualbox providers.

The error message is misleading - I get told:

    The box you're attempting to add doesn't support the provider
    you requested. Please find an alternate box or use an alternate
    provider. Double-check your requested provider to verify you didn't
    simply misspell it.

    If you're adding a box from HashiCorp's Atlas, make sure the box is
    released.

    Name: ubuntu/trusty32
    Address: https://atlas.hashicorp.com/ubuntu/trusty32
    Requested provider: ["vmware_desktop", "vmware_fusion", "vmware_workstation"]

However the provider is actually set to virtualbox, the Vagrantfile hasn't changed since before the upgrade and the base box does list as supporting virtualbox  (`ubuntu/trusty32                   (virtualbox, 14.04)`)

The vagrant file is as follows:

    Vagrant.configure("2") do |config|
    
        # Enable the Puppet provisioner, with will look in manifests
        config.vm.provision :puppet do |puppet|
            puppet.manifests_path = "puppet/manifests"
            puppet.manifest_file = "default.pp"
            puppet.module_path = "puppet/modules"
        end
    
        # Every Vagrant virtual environment requires a box to build off of.
        config.vm.box = "ubuntu/trusty32"

        # Forward guest port 80 to host port 8888 and name mapping
        config.vm.network "private_network", ip: "192.168.50.3"

        config.vm.synced_folder "web/", "/vagrant/web/", type: "nfs"
        config.vm.synced_folder "database/", "/vagrant/database/", type: "nfs"
    
        config.vm.provider "virtualbox" do |v|
          v.memory = 380
          v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end

        config.vm.provision "shell",
            inline: "echo Box up and provisioned"
    end

I've been able to fix my virtualbox projects with "VBoxManage list vms" then manually creating the matching id file, but it's a pain!

**Comment by mitchellh** [comment]
Hm, I just tried to reproduce this and wasn't able to. We also have unit tests around this, which leads me to believe its an edgier-case than this leads me to think. Did you have the VM already created? Can you reproduce it again or is it no longer possible?

If you _didn't_ have the VM created, this would make sense because the default provider logic that is new in 1.7 would prefer VMware (which it looks like its trying to get). But if you _do_ have the VM created, then it should've preferred the already-created provider whatever it was (in this case it sounds like VirtualBox).

Unfortunately, I need more repro steps to be able to fix this...

**Comment by bdgeorge** [comment]
Thanks for looking into it - the VMs did already exist, this particular VM given here also suffers from the issue #2134 with `Shared folders that Puppet requires are missing on the virtual machine.` on each provision attempt, forcing me to do a `vagrant reload --provision` each time I want to re-provision it.

However the bug applies to every other virtualbox VM as well, most of which don't have the second issue so that may be a red herring.

If I go to another Virtualbox Vagrant project altogether that I haven't opened since the upgrade and do a `vagrant status` I see the following:

```
Current machine states:

default                   not created (vmware_fusion)
```
If I look at the file structure of the .vagrant directory it's as follows:
![image](https://cloud.githubusercontent.com/assets/562621/5621180/170456ea-9587-11e4-91a0-693724760bb2.png)
No ID files or anything at all other than directories.
However If I look at the file structure for a pre-existing Vmware fusion Vagrant machine the ID files etc all exist as expected.

So it looks as if:
1) everything is now defaulting to the vmware fusion provider and 
2) the upgrade deleted all the files in the machines/default/virtualbox directories - was there some change to the file schema that an upgrade script handled?

My setup is OSX Yosemite, standard Osx Ruby, Vagrant with vagrant-librarian-chef (0.2.1), vagrant-librarian-puppet (0.7.1), vagrant-share (1.1.4, system), vagrant-vmware-fusion (3.1.0) - unfortunately I can't tell you what version of Vagrant I _used_ to be on prior to upgrade, it was not far behind the latest though.

**Comment by roelkok** [comment]
I'm having a similar problem occuring recently. After executing `vagrant suspend` the association is lost. The 'machines/default/virtualbox' folder is empty. Odd thing is this does not happen always. The VM is still listed in The VirtualBox GUI btw

My env
Vagrant 1.7.1
Windows 7
VirtualBox 4.3.20.96997

**Comment by hdeadman** [comment]
This is probably a different issue but its a scenario in which all the .vagrant files get deleted. 

I normally run vagrant from cmd.exe on Windows but if I run it from a unix shell (cygwin bash or migw32 shell for git) it wipes out all the files under .vagrant (but not the directories). I just type "vagrant status" from cygwin bash and all the machines show up as "not created" because all the .vagrant files get deleted. I can echo -n the uuid to recreate the "id" file and then I am able to use vagrant in cmd.exe.

I am running Vagrant 1.7.2 on Windows 7, VirtualBox 4.3.20.96997

**Comment by kikitux** [comment]
@hdeadman

your issue looks different to me.

Send an email to the mailing list, happy to assist.

basically in some windows the HOME of the shell and the home of the
cmd/windows are different, so how virtualbox works, they don't know each
other..

usually happen with windows under ms domain

on bash do  echo $HOME

and on windows cmd, check the output of 'set' or 'env'

send those to the mailing list

**Comment by azylman** [comment]
I also just had this issue, on Vagrant 1.7.2 and OSX 10.10.2. I ran `vagrant halt`, and later when I `vagrant up` it provisioned a new box.

**Comment by charginghawk** [comment]
I ran into this on Vagrant 1.7.2 and OSX 10.9.5. It happened when I was messing around with port forwarding to try to get https working. In particular, I think it was caused by temporarily removing this setting:

config.vm.network "private_network", ip: "192.168.50.5"

I fixed with the solution described here:

https://github.com/mitchellh/vagrant/issues/5144

**Comment by mitchellh** [comment]
This should be fixed in master.

**Comment by azylman** [comment]
This doesn't look like it's fixed - I just had this problem on vagrant 1.7.4 and VirtualBox 5

**Comment by haveaguess** [comment]
This has just happened to me in 1.7.4 as well, no crash though just a restart

I did however notice that my resources were drained which is what prompted the restart ('couldnt fork process' - file handle limits?)

**Comment by killerwolf** [comment]
I am having similiar issues

VMs under Vbox appears 'aborted' and under Vagrant 'not created'


My specs:
OSX maverick
vagrant 1.74
VBox 5.0.0

**Comment by azylman** [comment]
This just happened to me again with vagrant 1.8.1 and virtualbox 5. Since people are still having this problem, can we re-open the issue?

**Comment by xjschwen** [comment]
I run vagrant 1.8.1 on 3 Jenkins servers Hosts each hosting 3 vms

MS updates rebooted the servers last night and 4 lost associations and 5 did not.

Vagrant 1.8.1, Virtual box 5.20, Windows 8.1 enterprise

**Comment by DMNSteve** [comment]
Happened to me also.

OS X El Capitan 10.11.4
Vagrant 1.8.1
VirtualBox 5.0.18

My guest become unresponsive, so ran a `vagrant reload`.

**Comment by pearcec** [comment]
Happening on

Windows 7
Vagrant 1.9
Virtualbox 4.2.12 (Wow should I upgrade?)
Guest RHEL 6.x and Windows 2012R2
