### ISSUE TITLE
VirtualBox 5.0 not supported - Add Greater Than or Ignore Option

### ISSUE THREAD

**Issue by RickDavis84** [mitchellh/vagrant#5572]
I'm no longer able to use vagrant after upgrading to the new VirtualBox 5.0 Beta.  Please change the version checking mechanism to a >= check or add an option to ignore the version checking all together.

C:\>vagrant -v
Vagrant 1.7.2

C:\Program Files\Oracle\VirtualBox>VBoxManage.exe -v
5.0.0_BETA1r99371

C:\>vagrant up trusty64
The provider 'virtualbox' that was requested to back the machine
'trusty64' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3

**Comment by michaeldhopkins** [comment]
I'm very new to the Vagrant codebase, but it seems like each version needs to have its own drivers, /plugins/providers/virtualbox/driver/version_5_0.rb would need to be made. The 4.x driver files aren't all identical. Does anyone know what changes would need to be made for 5?

Alternately, what would be involved in switching to one driver file with feature detection?

**Comment by PhilipeLouchtch** [comment]
Well I had the same issue but I managed to get it running.

Step 1: Copy the `version_4_3.rb` file in `%vagrant_install_dir%\embedded\gems\gems\vagrant-1.7.2\plugins\providers\virtualbox\driver` to `version_5_0.rb` and edit the class name of the copied file to be "version_5_0"

Step 2: Modify the "meta.rb" file in the `virtualbox\driver` folder by adding `,5.0" => Version_5_0` to the `driver_map` hashmap (line 48).

Step 3: Modify the `plugin.rb` file in the `providers\virtualbox` directory (up one directory from where we were) and add the following line under line 47: `autoload :Version_5_0, File.expand_path("../driver/version_5_0", __FILE__) `

You're done.

**Comment by michaeldhopkins** [comment]
Thanks, Philipe. Do you mind if I make that a PR or would you rather?

**Comment by PhilipeLouchtch** [comment]
I'm unfamiliar with that abbreviation ('PR') in this context, but if you mean some kind of a 'pinned post', 'announcement', 'wiki entry' or whatever; go ahead.

I also wonder if it might have been even easier to simply skip Step 1 and 3 whilst adding the 5.0 mapping to the Version_4_3. So `,5.0 => Version_4_3`. This would probably be the easiest quick-and-dirty way of test driving VirtualBox 5.0 with Vagrant.

**Comment by michaeldhopkins** [comment]
Sorry, I meant a pull request. That would be faster for personal use, but I am guessing since they'll need Version_5_0 eventually for whatever quirks come up, your first method is the best way.

**Comment by PhilipeLouchtch** [comment]
Sure, go ahead!






From: Michael Hopkins
Sent: ‎Wednesday‎, ‎April‎ ‎15‎, ‎2015 ‎4‎:‎37‎ ‎PM
To: mitchellh/vagrant
Cc: Philipe Louchtch - de Raadt





Sorry, I meant a pull request. That would be faster for personal use, but I am guessing since they'll need Version_5_0 eventually for whatever quirks come up, your first method is the best way.

**Comment by sodabrew** [comment]
Works for me - @michaeldhopkins will you open a PR on this?

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/pull/5647

**Comment by virgofx** [comment]
:+1:

**Comment by morrisonbrett** [comment]
@PhilipeLouchtch this work around worked for me (Windows 10).  Thx.  Now waiting for 1.7.3...

**Comment by cfarrell81** [comment]
@PhilipeLouchtch worked for me (windows 7), cheers.

**Comment by rickw** [comment]
VirtualBox 5 is no longer beta 5.0.0r101573

**Comment by sethvargo** [comment]
VirtualBox 5 support is merged to master and will be released either today or tomorrow. Thanks!

**Comment by rickw** [comment]
thanks!!! 👍

**Comment by seansch** [comment]
What a coincidence, I am in the process of installing a vagrant box on VirtualBox5 currently and just ran into this issue, thanks.

**Comment by jverdeyen** [comment]
Any update about the next release? Thx!

**Comment by PhilipeLouchtch** [comment]
@jverdeyen Don't want to sound condescending but if you really need VirtualBox 5.0 support _right now_, either do the workaround discussed here or pull the ruby scripts from the development branch.

Questions regarding the release schedule of vagrant should be placed somewhere else.

**Comment by jverdeyen** [comment]
Ok, thanks. I installed the latest Vagrant and Virtualbox 5.0 successful from hombrew (cask).

**Comment by mitchellh** [comment]
We released vagrant 1.7.3 with virtual box 5 support a couple days ago.

**Comment by rockaBe** [comment]
:+1:

**Comment by BrainBuzzer** [comment]
Thanks Man

**Comment by vitr** [comment]
:+1:

**Comment by marcofranssen** [comment]
Still not working for my boxes which worked before...

```shell
==> default: Mounting shared folders...
    default: /vagrant => C:/Repositories/dev-vagrant-box
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chown `id -u vagrant`:`id -g vagrant` /vagrant

Stdout from the command:



Stderr from the command:

stdin: is not a tty
chown: changing ownership of `/vagrant': Not a directory
```

Any ideas?

**Comment by sethvargo** [comment]
Hi @marcellodesales - you are experiencing a different issue (https://github.com/mitchellh/vagrant/issues/5933), which has been fixed in Vagrant 1.7.4 Sorry about the regression.

**Comment by jcicero518** [comment]
I can confirm that updating Vagrant takes care of VirtualBox 5.x, at least in my case. I was running Vagrant 1.7.2, and Virtual Box is 5.0.26.

Now I'm on Vagrant 1.8.5 and no more:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3

**Comment by WayneZhouChina** [comment]
Thanks, It's good for me

**Comment by ananthaponnusamy** [comment]
Thanks, The same fix is working for 5.1 too..
