### ISSUE TITLE
vagrant docker-run shows "cannot enable tty mode on non tty input" on linux mint 17.1

### ISSUE THREAD

**Issue by sballert** [mitchellh/vagrant#5718]
OS: Linux mint 17.1
Vagrant: 1.7.2
Docker: 1.6.2, build 7c8fca2

I test Vagrant together with Docker as provider.  The Vagrantfile looks like this: 

``` ruby
ENV['VAGRANT_DEFAULT_PROVIDER'] ||= 'docker'

Vagrant.configure("2") do |config|
    config.vm.define "test_run" do |app|
        app.vm.synced_folder ".", "/vagrant", disabled: true
        app.vm.provider "docker" do |d|
            d.name = "test_run"
            d.image = "ubuntu:14.04"
        end
    end
end
```

When I run `vagrant docker-run test_run -t -- /bin/bash`,  I get the following message:

``` text
==> test_run: Creating the container...
    test_run:   Name: test_run_1431682004
    test_run:  Image: ubuntu:14.04
    test_run:    Cmd: /bin/bash
    test_run:  
    test_run: Container is starting. Output will stream in below...
    test_run:  
time="2015-05-15T11:26:44+02:00" level=fatal msg="cannot enable tty mode on non tty input" A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: ["docker", "run", "--name", "test_run_1431682004", "-i", "-t", "--rm=true", "ubuntu:14.04", "/bin/bash", {:notify=>[:stdout, :stderr]}]

Stderr: time="2015-05-15T11:26:44+02:00" level=fatal msg="cannot enable tty mode on non tty input"
```

When I run `docker run --name test_run_1431682697 -i -t --rm=true ubuntu:14.04 /bin/bash`, everthing works. 

[gist with debug infos](https://gist.github.com/SBallert/74594329dd4e92bdfcfe)

**Comment by mitchellh** [comment]
This is fixed on master

**Comment by nilakhya-gl** [comment]
this issue is not fixed, still occuring

**Comment by nilakhya-gl** [comment]
for test case  do this:
```
vagrant docker-run be874ed -t -- ls | wc -l
```
following error is shown : 

```
A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: ["docker", "run", "--name", "vag_rant_default_1437835197_1437835197", "-v", "/home/developer/vag_rant:/vagrant", "-i", "-t", "--rm=true", "c497e8609d22", "ls", {:notify=>[:stdout, :stderr]}]

Stderr: time="2015-07-25T20:09:57+05:30" level=fatal msg="cannot enable tty mode on non tty input" 


Stdout: 
9
```

**Comment by caspark** [comment]
Likewise - I'm still having this problem with Vagrant 1.7.4 and Docker 1.7.1 on Ubuntu 14.04.

**Comment by kddubb** [comment]
+1 Vagrant 1.7.2, Docker version 1.8.2, build 0a8c2e3, Ubuntu 14.04

If it was fixed on master, can you let us know when it makes it into a stable release?

**Comment by apollovy** [comment]
I figured out that using both --rm and -t results in weird behavior on my OS X 10.10.5:
1. Using --rm/-к works ok
2. Using --tty/-t works ok, too
3. Using -t/--tty AND THEN -r/--rm results in error
4. Using -r/--rm AND THEN -t/--tty results in no "-i -t" flags provided to docker
https://gist.github.com/apollovy/dbd0dae7f05dbc2ed29b

**Comment by hunterboerner** [comment]
This is still not fixed.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
