### ISSUE TITLE
 Command: ["hostonlyif", "create"] error with windows 10

### ISSUE THREAD

**Issue by erdemece** [mitchellh/vagrant#6059]
I have virtualbox 5.0 + vagrant 1.7 + phpuppet I'm having this problem. Could it be vagrant related? Because other virtual machines like ubuntu, macos, windows are working fine. Only vagrant machines have problem.

Every time I do vagrant up windows asks me to allow virtualbox then I receive following error on my console.

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

> Command: ["hostonlyif", "create"]

> Stderr: 0%...
> Progress state: E_FAIL
> VBoxManage.exe: error: Failed to create the host-only adapter
> VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
> VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 70 of file VBoxManageHostonly.cpp

**Comment by bhouston** [comment]
I am getting this exact error on two machines with Windows 10 + virtualbox 4.x/5.0 + vagrant 1.7.

**Comment by bhouston** [comment]
Appears to be a problem with VirtualBox + Windows 10 and they say there is a patch available but no new official version of VirtualBox yet:

https://www.virtualbox.org/ticket/14040

**Comment by guilhermemarconi** [comment]
@bhouston you installed this patch? it worked? if so, how can I install it?

[too many questions :laughing:]

**Comment by bhouston** [comment]
I understand applying the patch is difficult because it requires modification of a cert signed driver.  I'm not going to try that for the first time today.  I think the key is to exert pressure on VirtualBox to prioritize this fix -- I've tweeted at them about it today and I've posted on that bug (I'm doing that right now), I encourage you to also pressure them in some way as well -- we all need this fixed ASAP.

**Comment by dvh** [comment]
I tweeted them twice since yesterday but no response at all. It frustrates me that the VB issue was submitted 4 months ago, so it shouldn't be a surprise to them.

However, I've found this workaround on multiple places:

1. remove the line setting the private network in the vagrant file
2. remove the line `b.use ClearNetworkInterfaces` in `\Vagrant\embedded\gems\gems\vagrant-1.7.4\plugins\providers\virtualbox` (it's on line 64 in 1.7.4 at least)
3. vagrant up
4. vagrant halt
5. in VB's general settings, edit the host-only adapter manually and set the preferred IP
6. make sure this host-only adapter applies to the current machine
7. vagrant up

This worked for me, however I can't get samba to work. I hope this will be fixed by the same VB release otherwise I'm still screwed :(

**Comment by guilhermemarconi** [comment]
@dvh you use a third party box or your own? I use Scotch Box and don't know if it would break the box and bring me more problems. :pensive: 

About VirtualBox on Twitter, I didn't get any response, but I tweeted about 30 minutes ago.

**Comment by dvh** [comment]
I use my own. But I quit it also because I can't work without a working samba share :)

**Comment by dmdnkv** [comment]
The same problem: **Windows 10 RTM + Vagrant 1.7.4 + Virtual Box 5.0**

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 70 of file VBoxManageHostonly.cpp

**Comment by stremann** [comment]
The same from my side:

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended in
fo not available)
VBoxManage.exe: error: Context: "int __cdecl handleCreate(struct HandlerArg *,in
t,int *)" at line 66 of file VBoxManageHostonly.cpp

**Comment by tonygriv** [comment]
The same!

**Comment by shadowfolder** [comment]
Can't start genymotion! Same prombleb! Fix this shit please bro

**Comment by hectorgimenez** [comment]
Same problem here, but seems this bug is not a priority for the VirtualBox team...

**Comment by rootpd** [comment]
Appending to @dvh's temporary solution, I had to comment out also the next line. In my case commenting this helped:

```ruby
b.use PrepareNFSSettings
#b.use ClearNetworkInterfaces
#b.use Network
b.use ForwardPorts
```

However bear in mind, that **this is only temporary solution** and will probably force you set up the network adapters manually via VirtualBox GUI if they weren't set up correctly before.

**Comment by bhouston** [comment]
@rootpd, your workaround outlined in this comment is the first one that worked for me: https://github.com/mitchellh/vagrant/issues/6059#issuecomment-126655918  Thank you so much!

**Comment by lewins** [comment]
@rootpd, it worked! Nice temporary fix!

**Comment by lewins** [comment]
Coz `private_network` doesnt work (temporary) i needed to modify my Vagrantfile to forward some ports to see my website:
`config.vm.network :forwarded_port, guest: 80, host: 8080`

And in Windows access with: http://127.0.0.1:8080

**Comment by hypertexture** [comment]
Thanks @lewins - that port forwarding edit above has got me up and running. Vagrant up gave me a load of "default: Warning: Remote connection disconnect. Retrying..." notices but it booted in the end :)

**Comment by aaronsturm** [comment]
After @rootpd and @lewins changes, I keep receiving "Warning: Authentication failure. Retrying..." errors and it eventually times out. This configuration is rom https://puphpet.com/. Any help would be appreciated. Thanks!

**Comment by lewins** [comment]
Im not using puphet but i think your ssh auth keys are not set properly. check ur `~/.ssh/` folder

**Comment by guilhermemarconi** [comment]
VirtualBox answered [my tweet][1]. Look: https://twitter.com/virtualbox/status/627187142238838784

After all that, I found a way to work without depend of Vagrant and VirtualBox with BrowserSync and it's working perfectly.

I hope that this VirtualBox issue is solved ASAP for you guys get back to work soon! :facepunch: 

[1]:https://twitter.com/virtualbox/status/627187142238838784

**Comment by aaronsturm** [comment]
@lewins - It's supposed to use the \puphpet\files\dot\ssh keys. At least that's how it normally works with a Puphpet install. Not sure what's happening now...

**Comment by venimus** [comment]
Another solution is to manually create a Host-Only Adapter from VirtualBox GUI (or using VirtualBoxManage). You will get error even when manually add it (because of the same VirtualBox bug) but the adapter will be created properly.

Then specify the `IP` and the adapter `name` in your Vagrantfile

`config.vm.network "private_network", ip: "169.254.46.99", name: "VirtualBox Host-Only Ethernet Adapter"`

The trick is that specifying `name` will skip creating of virtual adapters along with this error.
Don't comment in vagrant source files, you skip a ton of other important things.

**Comment by aaronsturm** [comment]
@venimus Thanks. I tried that but I'm still getting the same error "default: Warning: Authentication failure. Retrying..."

**Comment by venimus** [comment]
@aaronstum May be it is a configuration issue. Check if both IPs are the same in Vagrantfile and VirtualBox adapter.

**Comment by dvh** [comment]
There is a fix available! I've tested it and it works with VB 5 and Vagrant 1.7.4: https://www.virtualbox.org/ticket/14040

**Comment by venimus** [comment]
I probably was not clear. The IP in Vagrantfile should be in the same network as the hostonly adapter but should not be the same.

**Comment by tonygriv** [comment]
With this .exe fix after `vagrant up` I have another error message:

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "ipconfig", "VirtualBox Host-Only Ethernet Adapter #7", "--ip", "192.168.56.1", "--netmask", "255.255.255.0"]

Stderr: VBoxManage.exe: error: The host network interface with the given name could not be found
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component Host, interface IHost, callee IUnknown
VBoxManage.exe: error: Context: "FindHostNetworkInterfaceByName(name.raw(), hif.asOutParam())" at line 218 of file VBoxManageHostonly.cpp
VBoxManage.exe: error: Could not find interface 'VirtualBox Host-Only Ethernet Adapter #7'

**Comment by lewins** [comment]
@tonygriv same here ))):

**Comment by erdemece** [comment]
Hi, thanks everyone.

My solution is here;
From Virtualbox you can't create host-only network because it gives you same error ""E_FAIL (0x80004005)"" but when you do vagrant up from your console it creates host-only networks but with different (random) IP without DHCP Server. You can edit one of those host-only network and attach to your virtual machine that you use with vagrant.

my ip in my vagrant file is 192.168.56.102 and these are my settings.

![image](https://cloud.githubusercontent.com/assets/360814/9025804/7a6b30bc-390d-11e5-8c76-3afa0b172e5b.png)

![image](https://cloud.githubusercontent.com/assets/360814/9025805/83b457b6-390d-11e5-9eba-fa1865b25673.png)

**Comment by tonygriv** [comment]
I don't see any host-only networks :(

**Comment by jaminday** [comment]
With the fix at https://www.virtualbox.org/ticket/14040 I get the same error as @tonygriv when running `vagrant up`.

@erdemece your solution didn't work for me. If I create a new host-only adapter through Virtualbox GUI, as soon as I close the preferences window Virtualbox forgets about it (even though the adapter is still present in Device Manager). I can't attach it to the VM as it's no longer recognized.

**Comment by jaminday** [comment]
Update: Downgraded Virtualbox from 5.0 to 4.3 and now it works using the fix mentioned above (Windows 10/Vagrant 1.7.4).

**Comment by tonygriv** [comment]
I have VB 4.3 and it's still not working :(

**Comment by negativefix** [comment]
I am also getting the same error with VB 4.3.

**Comment by gonzd2** [comment]
For anyone still having issues:
My Setup:
Windows 10 Home
VB 4.3.24
Vagrant 1.74
Ubuntu 14.0.4

I added the following line on my Vagrantfile

config.vm.network "forwarded_port", guest: 80, host: 8080
config.vm.network "private_network", ip: "55.55.55.5", name: "VirtualBox Host-Only Ethernet Adapter #4"
config.vm.network "public_network", ip: "192.168.0.45"

Additionally onthe VB GUI
File>Preferences>Network
Made sure there was an adapter matching the name on the Vagrantfile for the private_network

On the VB machine enabled Adapter 2
Attached to: Host-only Adapter
Name: VirtualBox Host-Only Ethernet Adapter #4

Ran fix https://www.virtualbox.org/ticket/14040
executed Vagrant up

once the machine was up closed the fix

**Comment by slipnox** [comment]
Hi guys,

I am Windows 10 Pro was fighting with the issue too, download the mentioned fix here https://www.virtualbox.org/ticket/14040 and follow this steps:

- Install latest VM 5.0
- Install latest Vagrant 1.7.4
- Restart the System
- Run the fix
- Vagrant up

Hope helps.

**Comment by sirolei** [comment]
@slipnox Thanks! It works very well.

**Comment by lokothodida** [comment]
@gonzd2 & @slipnox : when I run the fix I get a message from Windows (in a Metro modal dialog) saying

```
This app can't run on your PC
To find a version for your PC, check with the software publisher.
```

This is whether I run it normally or as an administrator. My setup is:

* Windows 10 Home (also upgraded from 8.1)
* Vagrant 1.7.4
* VirtualBox 5.0

**Comment by BinaryKitten** [comment]
btw the "fix"  executable listed on https://www.virtualbox.org/ticket/14040 - is an executable that adds a delay to an executing thread, it's not a patch against VirtualBox or a thing that will fix the issue, just acts as an intermediary and temporary solution.

**Comment by BinaryKitten** [comment]
As a Heads up, https://www.virtualbox.org/ticket/14040 now has a Test build reported to correct the issue: VirtualBox-5.0.1-101902-Win.exe. It's reported by michaln on https://www.virtualbox.org/ticket/14040#comment:55

Please do go test and report back to them on your success.

**Comment by lokothodida** [comment]
@BinaryKitten: thanks for the links. **michaln**'s new build and **Yirkha**'s 32-bit workaround both seem to get around this specific issue for me (so `vagrant up` gets past the "Preparing network interfaces based on cconfiguration" section), but both solutions lead into this [error](https://github.com/mitchellh/vagrant/issues/2157) when the VM tries to boot. I've tried setting up the same VMs on an Ubuntu host and they work fine there, so it is an issue in Windows 10.

**Comment by jaminday** [comment]
FWIW the test build VirtualBox-5.0.1-101902-Win.exe only worked for me when I set Virtualbox to run in Windows 8 compatibility mode. 

Here are the steps I followed:
1. Uninstalled any leftover VBox Host-Only Network adapters through Device Manager
2. Set `config.vm.network "private_network", ip: "192.168.50.4", name: "VirtualBox Host-Only Ethernet Adapter"` in my Vagrantfile
3. Enabled Win8 compatibility mode for VirtualBox 
4. Created a new Host-Only Network via VBox GUI, set the IP address manually to 192.168.50.4 (matching my private network config in Vagrantfile). Basically adapt settings in @erdemece's screenshots above for your IP.
Note: Win8 compatibility mode seems necessary for the new adapter to 'stick'. Otherwise VirtualBox forgets it as soon as the window is closed (for me at least).
5. `vagrant up --provision`


Note that the first time I ran `vagrant up` I received the following error
```The specified host network could not be found: 'VirtualBox Host-Only Ethernet Adapter.'
If the name specification is removed, Vagrant will create a new
host only network for you. Alternatively, please create the
specified network manually.```

On a whim I tried disabling TCP/IPv6 for the VirtualBox Host-Only Ethernet Adapter and then it worked, but I've since re-enabled IPv6 and multiple `vagrant halt`, `vagrant up [--provision]` attempts have been fine. So not sure if it was necessary.

**Comment by Festum** [comment]
@jaminday After the steps I meet crash when open vbox gui every times.

**Comment by erdemece** [comment]
test build fixed for me

https://www.virtualbox.org/download/testcase/VirtualBox-5.0.1-101902-Win.exe

**Comment by jaminday** [comment]
@Festum have you tried reinstalling Virtualbox?

**Comment by tonygriv** [comment]
@erdemece, VB shows an error renaming the environment, because this name is already exists.

**Comment by BinaryKitten** [comment]
Hi Everyone, 

If you're having issues with VirtualBox and you've not changed Vagrant - surely the best place to report the problems is to VirtualBox.
Stating here crashes in VirtualBox won't get them resolved as @mitchellh can't fix them. (unless i'm missing something)

If we want VirtualBox to get this fixed, lets report our experiences of the "fix" etc to them

**Comment by ZackWard** [comment]
Confirming the work-around posted by @venimus worked for me. I changed the private network config in the Vagrantfile to read
> config.vm.network "private_network", ip: "192.168.10.10", name: "VirtualBox Host-Only Ethernet Adapter #3"

and then made sure that in the VirtualBox GUI, that adapter was set to IP 192.168.10.9. This is working for me. Thank you for the suggestion @venimus

**Comment by venimus** [comment]
If you are tracking Vagrantfile you could temporary change it, then use `vagrant suspend` instead of halt (or other way to stop it). Than you can discard the changes.

**Comment by antonybudianto** [comment]
Mine doesn't work too

Windows 10 Pro x86 (32bit)
Virtual Box 5.0.1 (test build)
Vagrant 1.7.4

still stucks at the very same Festum's error message
maybe the x86 is the problem since many x64 users succeed.

**Comment by saraf** [comment]
5.0.1 r101957 and Vagrant 1.7.4 still does not fix the problem for me. in my Vagrantfile I have config.vm.network "private_network", ip: "192.168.56.102" (ubuntu trusty box guest, windows 10 host) everytime I try to do a vagrant up, an error message pops up saying "Cannot rename connection. A connection with the name you specified already exists. Please specify a different name." After clicking OK  it creates a new Ethernet adapter with an incremented #number and the box does not boot up - What should be done?

**Comment by saraf** [comment]
5.0.1 r101957 and Vagrant 1.7.4 still does not fix the problem for me. in my Vagrantfile I have config.vm.network "private_network", ip: "192.168.56.102" (ubuntu trusty box guest, windows 10 host) everytime I try to do a vagrant up, an error message pops up saying "Cannot rename connection. A connection with the name you specified already exists. Please specify a different name." After clicking OK  it creates a new Ethernet adapter with an incremented #number and the box does not boot up.

**Comment by saraf** [comment]
The workaround by venimus works for preventing the creation of spurious Ethernet adapters.  (The trick is that specifying name will skip creating of virtual adapters along with this error.) Is this specification required behavior henceforth?

**Comment by venimus** [comment]
There is a check for provided `option.name` that skips creation of adapters.

**Comment by andyburton** [comment]
Finally working here with

Windows 10 Pro x64
VirtualBox 5.0.1r101902
Vagrant 1.7.4

**Comment by ZackWard** [comment]
I found a solution that doesn't involve any file modifications here: 

https://laracasts.com/discuss/channels/general-discussion/windows-10-vagrant-virtualbox-homestead/?page=5

Credit to pdcmoreira of the Laracast community for this solution.

Go to the C:\Program Files\Oracle\VirtualBox folder, right click on VirtualBox.exe, go to compatibility tab, check the "Run in compatibility mode" checkbox and choose Windows 7. Click OK to close the window.
Repeat for VBoxManage.exe and VBoxHeadless.exe

I set to Windows 8 compatibility, and was able to get my VM up and running without any file modifications.

**Comment by kshamsuddin** [comment]
gfhgfgf

**Comment by kshamsuddin** [comment]
Hi,
Finally it works but when I type the ip for example: 55.55.55.5 to chrome I got the following error:

This web page is not available
ERR_CONNECTION_REFUSED

I can ping that private ip from terminal with 0% loss. I edited the host file as :55.55.55.5 example.dev
 and tried to use that in chrome + firefox "example.dev" but no luck. Can't browse that from any browser. 

Thanks for any advice.

**Comment by riebling** [comment]
The latest versions of VirtualBox and Vagrant, combined, seem to still not fix the problem for me.
Changing the compatibility mode of the VirtualBox executables to Windows 7 did not help, either.
I'm jealous of those here who got it to work!

EDIT: If I use the specific VirtualBox version mentioned above (VirtualBox-5.0.1-101902-Win.exe), it got past the creating host-only network interface error, but still failed to boot the box the whole way. So it appears that the bleeding edge version of VirtualBox (VirtualBox 5.0.1r101957) is actually a regression to the original Host-only Network Interface error

Windows 10 Home (64 bit)
VirtualBox 5.0.1r101957
Vagrant 1.7.4

```
Error: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 70 of file VBoxManageHostonly.cpp
```

**Comment by bart** [comment]
Same here. I did try a bunch of things like different virtualbox versions, the fix, compatibility, installing as admin - everytime different errors. I'm currently hanging on a problem where I can't install virtualbox (VirtualBox-5.0.1-101902-Win.exe) anymore getting "Setup Wizard ended prematurely". I disabled the bridge networking during setup.

I'm also using Kaspkersky. Maybe another possible root for errors?

**Comment by lewins** [comment]
Works for me with:

Windows 10 Pro x64
VirtualBox 5.0.1-102010
Vagrant 1.7.4

**Comment by riebling** [comment]
Confirming VB 5.0.1-102010 for the win

**Comment by jag1989** [comment]
Windows 10 Home
VirtualBox 5.0.1-102010
Vagrant 1.7.4

Confirmed as working

**Comment by antonybudianto** [comment]
**Virtualbox 5.0.2** is available and it works well without modifying any files and hack the port, and it works on Windows 10 Pro **x86**

**Comment by tonygriv** [comment]
Still not working :(

**Comment by alexsouza** [comment]
Hey guys, this works for me : http://lezgro.com/blog/a-very-simple-fix-for-the-windows-10-and-vagrant-error/

**Comment by ljjackson** [comment]
@alexsouza Just upgraded to Windows 10 and followed the solution on the lezgro blog, worked a treat! Many thanks!

**Comment by GuruVoodoo** [comment]
venimus stumbled on the answer Specifiy as shown below in the Vagrantfile Leaving the line without a name causes the issue.

config.vm.network "private_network", ip: "169.254.46.99", name: "VirtualBox Host-Only Ethernet Adapter"

**Comment by lightinthedark** [comment]
For what it's worth, I was encountering the same problem with at freshly generated vagrant file from puphpet, and running Windows 7.

I was able to get it to work:
* updated vagrant to 1.7.4
* updated virtualbox from 4.3.30 to 4.3.32 (http://download.virtualbox.org/virtualbox/4.3.32/) - installed as administrator after Win said the initial installation may not have worked
* reboot
* start cmd as administrator
* cd ... 
* vagrant up

I can only presume that in those 2 minor VB versions something got patched. I don't know if the couple of "run as administrator" notes make a difference.

**Comment by mitchellh** [comment]
Yeah this is an unfortunate VirtualBox issue. I think there is enough Google-juice here to guide users. And new users appear to be mostly unscathed so I think VirtualBox has fixed this in later versions. Sorry folks!

**Comment by engine-go** [comment]
I modified the vagrantfile：
`config.vm.network "private_network", ip: "192.168.33.10"`
The console told me the following：

> There was an error while executing `VBoxManage`, a CLI used by Vagrant
> for controlling VirtualBox. The command and stderr is shown below.
> 
> Command: ["hostonlyif", "create"]
> 
> Stderr: 0%...
> Progress state: E_FAIL
> VBoxManage.exe: error: Failed to create the host-only adapter
> VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
> VBoxManage.exe: error: Context: "int __cdecl handleCreate(struct HandlerArg *,int,int *)" at line 66 of file VBoxManageHostonly.cpp

When I hide the configure,it work:
`# config.vm.network "private_network", ip: "192.168.33.10"`

> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Clearing any previously set network interfaces...
> ==> default: Preparing network interfaces based on configuration...
>     default: Adapter 1: nat
> ==> default: Forwarding ports...
>     default: 22 (guest) => 2222 (host) (adapter 1)
> ==> default: Booting VM...
> ==> default: Waiting for machine to boot. This may take a few minutes...
>     default: SSH address: 127.0.0.1:2222
>     default: SSH username: vagrant
>     default: SSH auth method: private key
> ==> default: Machine booted and ready!
> ==> default: Checking for guest additions in VM...
> ==> default: Mounting shared folders...
>     default: /vagrant => E:/VirtualBox
>     default: /vagrant_data => E:/VirtualBox/app
> ==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
> ==> default: flag to force provisioning. Provisioners marked to run always will still run.

**Comment by tuvietthao** [comment]
Turn off your Hyper-V

**Comment by Costanza** [comment]
Just FYI as I came across this trying to solve the problem, I am having this issue on a fresh Windows 10 install with Vagrant 1.8.1 and VirtualBox 5.0.14. Tried many workarounds but no dice yet.

**Comment by mattKendon** [comment]
Following an update to my Windows 10 machine last night, I get this issue now where I wasn't before.

Version 1511 (OS Build 10586.104)

**Comment by pgcd** [comment]
The workaround from @engine-go worked for me - I already had the interface (along with several spurious ones which I deleted), and I have the executables (Virtualbox.exe, SVC, Manage and Headless) to run in Win8 compatibility mode, so the solution may require at least those steps.

**Comment by danyunfu** [comment]
I upgraded VirtualBox and this is no longer an issue

**Comment by seperman** [comment]
@engine-go your solution worked for me but how do you set the ip of the VM then? Through the Virtualbox gui?

**Comment by shenqihui** [comment]
The key of the solution mention in https://www.virtualbox.org/ticket/14040 is to keep the fix program running when running `vagrant up` or `vagrant reload`.

Try it.

**Comment by LuisRamirezColin** [comment]
I had the same problem so i fixed this issue when im installing of new version to VM. I think it´s very funy because i tried the solution 14040 and not working for me.

**Comment by wallraks** [comment]
I got the same problem but I only restarted VirtualBox by restarting the whole machine and repeated the same process and it worked

**Comment by jfitzsimmons2** [comment]
FWIW, I had this issue, I tried uninstalled/re-installed VB, then had VB open when I did 'vagrant up' and it worked no problem. ¯\_(ツ)_/¯

**Comment by manjunath-coachthem** [comment]
I had exact same error on my mac. I tried reinstalling virtualbox and that fixed the issue.

**Comment by panchalkalpesh** [comment]
Following solution worked for me:

1. Goto `C:\Program Files\Oracle\VirtualBox\drivers\network\`
2. There are two folders, go inside both of them and right click on `.inf` and click **Install**
3. Head over to `Control Panel\Network and Internet\Network Connections`
4. Right click on Network Adapter and choose **Properties**
5. Click on **Install** => **Service**
6. Under Manufacturer choose **Oracle Corporation** and under Network Service, choose **VirtualBox NDIS6 Bridged Networking driver**
7. Ok and Close


*Preview*
![capture](https://cloud.githubusercontent.com/assets/1808686/26414679/ec690bde-407d-11e7-9d79-c60840cfc948.PNG)



Finally, run
````
vagrant up
````


Hope this helps you!
[Kalpesh Panchal](http://kalpeshpanchal.in)

**Comment by NingZaizai** [comment]
same issue, I just ran the fix file and the error still shown, any help would be thankful.

**Comment by IshtiaqAhsan** [comment]
@panchalkalpesh this worked like a Magic!!! Thanks a Zillion 🥇

**Comment by ldmuniz** [comment]
@lightinthedark solution works for me

**Comment by RafaelMLMacedo** [comment]
@panchalkalpesh solution worked great! Thanks

**Comment by naorzr** [comment]
@panchalkalpesh Someone give this man a medal. well as far as I understand the network adapter didn't install automatically on my machine since kaspersky was on at the time I installed vbox, so.. if you can just reinstall vbox with kaspersky off, does the same.

**Comment by Rodri9o** [comment]
@panchalkalpesh - your solution worked. Thank you very much!
