### ISSUE TITLE
Vagrant issues with bundler....

### ISSUE THREAD

**Issue by ddreggors** [mitchellh/vagrant#6158]
Latest vagrant (1.7.4 as of this writing) does not support bundler 1.10.6...

The error message is shown below:

Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    vagrant (= 1.7.4) ruby depends on
      bundler (<= 1.10.5, >= 1.5.2) ruby

  Current Bundler version:
    bundler (1.10.6)

**Comment by sethvargo** [comment]
Hi @ddreggors 

The recommended way to run Vagrant is via the official Vagrant installers on https://vagrantup.com which do not interfere with your system Ruby or installed gems.

Please see also: https://github.com/mitchellh/vagrant/pull/6111#issuecomment-128732550

**Comment by ddreggors** [comment]
I did install vagrant from RPM on the download page of this site. 

Note no gem in following commands:

```
[ddreggors@mobile-tek git-cookbook (ddreggors - master)  ]$ rpm -q vagrant
vagrant-1.7.4-1.x86_64
[ddreggors@mobile-tek git-cookbook (ddreggors - master)  ]$ gem list vagrant

*** LOCAL GEMS ***

kitchen-vagrant (0.18.0)
```

**Comment by sethvargo** [comment]
Hi @ddreggors 

Just because an issue is closed doesn't mean we can't continue discussion :smile:. How are you invoking the Vagrant command?

**Comment by ddreggors** [comment]
I am calling "kitchen create". I have a chef cookbook I am trying to serverspec tests on in vagrant via test-kitchen. If I uninstall the bundler gem and force install to use 1.10.5 all is well. However using the latest update of 1.10.6 cause the error seen above when running any kitchen commands.

**Comment by sethvargo** [comment]
Hi @ddreggors 

What is the output of `bundle show` on that project? Can you share the Gemfile please?

This does not look like a Vagrant issue. For the reasons described in https://github.com/mitchellh/vagrant/pull/6111#issuecomment-128732550, we cannot just upgrade bundler to a new version. However, Test Kitchen shouldn't be using the vagrant gem and should be using the system gem. I wonder if Test Kitchen isn't correctly resetting the Ruby environment, which is causing this issue.

Are you using the ChefDK?

**Comment by ddreggors** [comment]
Bundle show command:
```
$ bundle show
Gems included by the bundle:
  * addressable (2.3.8)
  * berkshelf (3.3.0)
  * berkshelf-api-client (1.3.0)
  * buff-config (1.0.1)
  * buff-extensions (1.0.0)
  * buff-ignore (1.1.1)
  * buff-ruby_engine (0.1.0)
  * buff-shell_out (0.2.0)
  * bundler (1.10.5)
  * celluloid (0.16.1)
  * celluloid-io (0.16.2)
  * cleanroom (1.0.0)
  * coderay (1.1.0)
  * dep-selector-libgecode (1.0.2)
  * dep_selector (1.0.3)
  * erubis (2.7.0)
  * faraday (0.9.1)
  * ffi (1.9.10)
  * formatador (0.2.5)
  * guard (1.8.3)
  * guard-kitchen (0.0.2)
  * hashie (2.1.2)
  * hitimes (1.2.2)
  * httpclient (2.6.0.1)
  * json (1.8.3)
  * kitchen-vagrant (0.18.0)
  * listen (1.3.1)
  * lumberjack (1.0.9)
  * method_source (0.8.2)
  * minitar (0.5.4)
  * mixlib-authentication (1.3.0)
  * mixlib-log (1.6.0)
  * mixlib-shellout (2.1.0)
  * multipart-post (2.0.0)
  * net-http-persistent (2.9.4)
  * net-scp (1.2.1)
  * net-ssh (2.9.2)
  * net-telnet (0.1.1)
  * nio4r (1.1.1)
  * octokit (3.8.0)
  * pry (0.10.1)
  * rb-fsevent (0.9.5)
  * rb-inotify (0.9.5)
  * rb-kqueue (0.2.4)
  * retryable (2.0.2)
  * ridley (4.2.0)
  * safe_yaml (1.0.4)
  * sawyer (0.6.0)
  * semverse (1.2.1)
  * sfl (2.2)
  * slop (3.6.0)
  * solve (1.2.1)
  * specinfra (2.41.1)
  * test-kitchen (1.4.2)
  * thor (0.19.1)
  * timers (4.0.1)
  * varia_model (0.4.0)
```

Gemfile contents:
```
$ cat Gemfile
source 'https://rubygems.org'

gem 'berkshelf'

group :development do  
  gem 'specinfra'
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
  gem 'guard', '~> 1.8'
  gem 'guard-kitchen'
end
```

**Comment by ddreggors** [comment]
I am using ChefDk yes, and as to using the vagrant gem... not sure how it can use the vagrant gem when that gem is not installed.

**Comment by sethvargo** [comment]
@fnichol hi :smile: 

So, I think kitchen-vagrant is at fault here, but I cannot reproduce this locally so I'm not sure. Does kitchen-vagrant full reset the original environment before shelling out to Ruby? I know there's a `Bundler.with_clean_env` somewhere, but I think you need to do something like restoring the original environment that existed before bundle ran, not just the bundle-specific env. I think thats `Bundler::ORIGINAL_ENV` or something like that.

**Comment by ddreggors** [comment]
@sethvargo you hit the nail on the head I think. I found that in the newer chefdk installs kitchen-vagrant is included. 

See: https://github.com/chef/omnibus-software/commit/98b0838cf0085b41539c4b2bbf47f9c089b7604e

Sadly I was unaware of this and also had the gem installed via bundler (see bundle show and gemfile above).

I also had the kitchen gem and the berkshelf gem installed. They were brought in as dependencies accidentally. Here is what gave this all away...


```
$ chef -v
Chef Development Kit Version: 0.7.0
chef-client version: 12.4.1
berks version: ERROR
kitchen version: ERROR
````

Note the error lines above.

So after uninstalling the berkshelf gem, the kitchen gem, and the kitchen-vagrant gem, removing all from Gemfile as well and running bundle update....


```
$ chef -v
Chef Development Kit Version: 0.7.0
chef-client version: 12.4.1
berks version: 3.2.4
kitchen version: 1.4.2
```

Now I updated bundler back to 1.10.6 and I can again run kitchen create/test/converge/verify/destroy :+1:

**Comment by sethvargo** [comment]
Hi @ddreggors 

I'm glad things are working again. I'm going to keep this open for a bit to see if @fnichol has any thoughts.

**Comment by tknerr** [comment]
@sethvargo @fnichol @danielsdeleo this might be what I'm seeing in #6176 as well

I'm using latest ChefDK 0.7.0 and Vagrant 1.7.4. 

I installed bundler 1.10.6 because the 1.10.0 one that ships with ChefDK fails on parallel bundle installs (see related chef/omnibus-chef#464 PR). 

Now whenever I run `bundle exec kitchen create` with the kitchen-vagrant driver I get this:
```
C:\Repos\_github\bills-kitchen\target\build\repo\vagrant-workflow-tests\playground\sample-toplevel-cookbook>bundle exec kitchen create 1204
-----> Starting Kitchen (v1.4.2)
-----> Creating <default-ubuntu-1204>...
       Vagrant experienced a version conflict with some installed plugins!
       This usually happens if you recently upgraded Vagrant. As part of the
       upgrade process, some existing plugins are no longer compatible with
       this version of Vagrant. The recommended way to fix this is to remove
       your existing plugins and reinstall them one-by-one. To remove all
       plugins:

           rm -r ~/.vagrant.d/plugins.json ~/.vagrant.d/gems

       Note if you have an alternate VAGRANT_HOME environmental variable
       set, the folders above will be in that directory rather than your
       user's home directory.

       The error message is shown below:

       Bundler could not find compatible versions for gem "bundler":
         In Gemfile:
           vagrant (= 1.7.4) x86-mingw32 depends on
             bundler (<= 1.10.5, >= 1.5.2) x86-mingw32

         Current Bundler version:
           bundler (1.10.6)
       This Gemfile requires a different version of Bundler.
       Perhaps you need to update Bundler by running `gem install bundler`?
       Could not find gem 'bundler (<= 1.10.5, >= 1.5.2) x86-mingw32', which is required by gem 'vagrant (= 1.7.4) x86-mingw32', in any of the sources.
```

I don't have Vagrant installed as a gem, so I'm wondering where that conflict is coming from.

Might well be something with kitchen-vagrant not properly resetting the environment, as @sethvargo suspected some comments above.

**Comment by Azolo** [comment]
I'm getting this whenever the `GEM_HOME` or `GEM_PATH` environment variables are set then `vagrant` is called.

Unsetting them fixes it and vagrant will run again.

**Comment by Azolo** [comment]
Sorry, I did some shoddy debugging. It's the `RUBYLIB` environment variable.

**Comment by mfischer-zd** [comment]
@sethvargo I agree with the caller here.  The vagrant binary (when installed via a native OS package) should take care to unset any environment variables that would conflict with its omnibus environment.

**Comment by Azolo** [comment]
Rereading what I said, I should have been more specific in what was happening for me.

I was running a `rake` task that shelled out to `vagrant` and `rbenv` was setting up my environment in that context. In which case I did restore the environment from before Bundler but it was actually `rbenv` that was changing it in this case. And shelling out via `sh "(unset RUBYLIB; vagrant up)"` did in fact fix it.

The short of it is that the issue isn't limited to (or likely even caused) by Bundler, but by tools that control and setup a overall `ruby` environment.

**Comment by sethvargo** [comment]
@mfischer-zd the issue isn't unsetting the environment, but _resetting_ it. It's not possible to just unset RUBYOPT, RUBYLIB, etc because then when a process tries to shellout to another non-omnibussed Ruby process it will fail since there's no Ruby env. 

What needs to happen is that the original calling environment needs to be restored. Vagrant is doing this as of 1.7.4, but it can only restore to the environment it was executed from. So in the case of TK, for example, Vagrant is only capable of restoring to the environment it was called from (which is TK's environment) - it doesn't know the pre-TK environment which is why this is impossible for Vagrant to solve.

**Comment by mfischer-zd** [comment]
@sethvargo What is Vagrant executing that needs the pre-Vagrant Ruby-related environment?  If nothing, I can't see the purpose of environment restoration.

**Comment by cpick** [comment]
I've run into the same issue using [Beaker](https://github.com/puppetlabs/beaker).

I've installed vagrant with the vagrantup.com provided Ubuntu 64bit package and used Bundler to install and load the Beaker gem.  Beaker attempts to `Open3.popen3("vagrant #{args}")` which then fails because Bundler has set the RUBYLIB environment variable.

I agree with @mfischer-zd's analysis: I believe that when an executable (like the omnibus vagrant) requires a particular environment to function properly, it's responsible for sanitizing its environment as needed.

There is already some precedent for this: the launcher currently clears RUBYOPT https://github.com/mitchellh/vagrant-installers/blob/master/substrate/launcher/main.go#L136 :

```go
// Unset any RUBYOPT, we don't want this bleeding into our runtime
newEnv["RUBYOPT"] = ""
```

I believe the right thing to do in this case is to do exactly the same with RUBYLIB.

**Comment by cpick** [comment]
I've created https://tickets.puppetlabs.com/browse/BKR-511 to track this on the Beaker side of things, but I strongly believe this ought to be fixed on Vagrant's end.

**Comment by mokhan** [comment]
I'm currently hitting the same issue:

```bash
λ bundle exec kitchen converge default-centos-71
-----> Starting Kitchen (v1.4.2)
-----> Creating <default-centos-71>...
       Vagrant experienced a version conflict with some installed plugins!
       This usually happens if you recently upgraded Vagrant. As part of the
       upgrade process, some existing plugins are no longer compatible with
       this version of Vagrant. The recommended way to fix this is to remove
       your existing plugins and reinstall them one-by-one. To remove all
       plugins:

           rm -r ~/.vagrant.d/plugins.json ~/.vagrant.d/gems

       Note if you have an alternate VAGRANT_HOME environmental variable
       set, the folders above will be in that directory rather than your
       user's home directory.

       The error message is shown below:

       Bundler could not find compatible versions for gem "bundler":
         In Gemfile:
           vagrant (= 1.7.4) ruby depends on
             bundler (<= 1.10.5, >= 1.5.2) ruby

         Current Bundler version:
           bundler (1.10.6)
       This Gemfile requires a different version of Bundler.
       Perhaps you need to update Bundler by running `gem install bundler`?
       Could not find gem 'bundler (<= 1.10.5, >= 1.5.2) ruby', which is required by gem 'vagrant (= 1.7.4) ruby', in any of the sources.
```

Is there anything that I can do in the interim to get past this error.

**Comment by dmp1ce** [comment]
I'm getting this error too trying to use an old version of Capistrano. As far as I can tell I do not have vagrant referenced in Gemfile.

```
$ cat Gemfile
source 'https://rubygems.org'

gem 'capistrano', '2.15.4'
gem 'railsless-deploy', '1.1.0'
gem 'capistrano-deepmodules'
```

**Comment by dmp1ce** [comment]
My issue is I was calling `vagrant ssh-config` inside my deployment script. My solution is to call unset RUBYLIB; just before calling vagrant like Azolo suggested.

I changed my code from
```
parse_options(`vagrant ssh-config`)
```
to
```
parse_options(`unset RUBYLIB; vagrant ssh-config`)
```

**Comment by richburroughs** [comment]
I'm having this issue with Beaker as well. I've had to stick to Bundler 1.10.5 as a workaround.

**Comment by fnichol** [comment]
Adding some (late) context to this thread, but we have a Bundler-busting release of [kitchen-vagrant 0.19](https://github.com/test-kitchen/kitchen-vagrant/blob/master/CHANGELOG.md#0190--2015-09-18) which was release 2015-09-18. With the key issues/pull requests being test-kitchen/kitchen-vagrant#190, test-kitchen/kitchen-vagrant#191, test-kitchen/kitchen-vagrant#197. Hope this helps for anyone else looking for a candidate solution!

**Comment by robinbowes** [comment]
I have a similar issue with beaker, using it for puppet module acceptance tests on OSX El Capitan

Downgrading bundler to 1.10.5 is my workaround too.

**Comment by charlieok** [comment]
I just ran into this as well. Yes, Bundler.with_clean_env should be the fix. However, that is broken in the current (v1.10.6) version of Bundler.

I believe the culprit is a bug in bundler: https://github.com/bundler/bundler/issues/3982

A fix was authored on September 8th: https://github.com/bundler/bundler/commit/42b507218fd910feb2a9756bc08dc41181a9d1c4

and was merged to bundler's master branch on September 19th: https://github.com/bundler/bundler/commit/a136afe15df46acc5445395a98f991dbd8641304

Bundler v1.10.6 was tagged on July 22nd: https://github.com/bundler/bundler/releases/tag/v1.10.6

So until we have a new Bundler release, I suppose a workaround will be necessary.

Here is what I did:

```ruby
    Bundler.with_original_env do

      # This hack can be removed once we update to a bundler version newer than
      # 1.10.6, assuming it includes a fix to the following issue:
      # https://github.com/bundler/bundler/issues/3982
      if ENV.key?("RUBYLIB")
        rubylib = ENV["RUBYLIB"].split(File::PATH_SEPARATOR)
        rubylib.shift # Remove the first path in the RUBYLIB list
        ENV["RUBYLIB"] = rubylib.join(File::PATH_SEPARATOR)
      end

      system command_string
    end
```

**Comment by onyxraven** [comment]
@charlieok I just now ran into this - where does this snippet go?

**Comment by richburroughs** [comment]
It's been fixed in Beaker. Just grab the latest Beaker.


Rich

**Comment by onyxraven** [comment]
Ah, not using beaker.  Since this is the vagrant issue I thought it was something more generic, since there was little context

**Comment by charlieok** [comment]
@onyxraven 
The snippet goes wherever you need to launch a child process (people sometimes say “shell out” though it seems more correct to say fork/exec). That's the “system command_string” line the the snippet, where command_string is the command you intend to run. The rest of the snippet code is there to remove the modifications made by an ancestor 'bundle' process, so your child process can run as though the ancestor 'bundle' process were not there.

There appears to be a v1.11.0 release of bundler in the works, with two 'preview' releases out (the latter just two days ago), which is encouraging. I see that the fix I mentioned previously is included in that release:

https://github.com/bundler/bundler/blob/v1.11.0.pre.2/lib/bundler.rb#L213-L217

So, once Bundler v1.11.0 is out, hopefully soon, I assume this issue will be resolved.

**Comment by onyxraven** [comment]
shoot, so I am using Rubber.

I tried wrapping all the system(): https://github.com/rubber/rubber/blob/master/lib/rubber/vagrant/provisioner.rb

though it already clears out RUBYLIB.  I made this change both in vagrant's gem as well as my local env.  I'm still getting the error.

**Comment by Azolo** [comment]
@onyxraven You'll have to set after rubber gets loaded, but before it calls `vagrant` directly.

**Comment by b-dean** [comment]
I have this problem even without test-kitchen. Using ruby 2.1.8 and bundler 1.11.2 and this `Gemfile`

```ruby
source 'https://rubygems.org'
gem 'bundler', '~> 1.11'
```

When I run `bundle exec vagrant` I get
```
Vagrant experienced a version conflict with some installed plugins!
This usually happens if you recently upgraded Vagrant. As part of the
upgrade process, some existing plugins are no longer compatible with
this version of Vagrant. The recommended way to fix this is to remove
your existing plugins and reinstall them one-by-one. To remove all
plugins:

    rm -r ~/.vagrant.d/plugins.json ~/.vagrant.d/gems

Note if you have an alternate VAGRANT_HOME environmental variable
set, the folders above will be in that directory rather than your
user's home directory.

The error message is shown below:

Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    vagrant (= 1.8.1) was resolved to 1.8.1, which depends on
      bundler (<= 1.10.6, >= 1.5.2)

  Current Bundler version:
    bundler (1.11.2)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (<= 1.10.6, >= 1.5.2)', which is required by gem 'vagrant (= 1.8.1)', in any of the sources.
```

If I make a little script called `clean_vagrant.sh` with

```bash
#!/bin/bash
unset RUBYLIB
vagrant
```

Then `bundle exec clean_vagrant.sh` works as expected. Maybe the vagrant launcher should reset the  `RUBYLIB` environment variable the [same way it does with `RUBYOPT`](https://github.com/mitchellh/vagrant-installers/blob/64c526165c6ffe5fdc170b5babb24a8498752016/substrate/launcher/main.go#L143-L144). I'm pretty sure that's part of the reason why that launcher exists, so vagrant will work despite whatever else might be going on w/ bundler or other rubies on the user's system.

**Comment by duzy** [comment]
Hi, I'm having exactly the same issue while doing `bundle exec vagrant up`:

```
Vagrant experienced a version conflict with some installed plugins!
This usually happens if you recently upgraded Vagrant. As part of the
upgrade process, some existing plugins are no longer compatible with
this version of Vagrant. The recommended way to fix this is to remove
your existing plugins and reinstall them one-by-one. To remove all
plugins:

    rm -r ~/.vagrant.d/plugins.json ~/.vagrant.d/gems

Note if you have an alternate VAGRANT_HOME environmental variable
set, the folders above will be in that directory rather than your
user's home directory.

The error message is shown below:

Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    vagrant (= 1.8.1) was resolved to 1.8.1, which depends on
      bundler (<= 1.10.6, >= 1.5.2)

  Current Bundler version:
    bundler (1.11.2)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (<= 1.10.6, >= 1.5.2)', which is required by gem 'vagrant (= 1.8.1)', in any of the sources.
```

**Comment by bibstha** [comment]
I've got the same problem while trying to build a custom plugin.

I'm using the latest bundler 1.11.2 while vagrant seems to be pinned to <= 1.10.6. Downgrading bundler helps. Any idea why it's pinned to 1.10.6?

**Comment by counterbeing** [comment]
Yeah, same issue here. Just using vagrant to host some services in a rails project and running into this. No sign of vagrant in the Gemfile at all. Not sure why this is tied to an older version of bundler.

**Comment by kenorb** [comment]
Related: #6798, #7193

**Comment by ozzyaaron** [comment]
I was getting the same output as @duzy 

One thing I've found that might help is that you can execute a bundle under specific version. 

`bundle _x.y.z_ [command]`

For me I simply use `bundle exec _1.10.6_ foreman start` which houses a `vagrant up` and this works now.

**Comment by chrisroberts** [comment]
Related: #7793

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
