### ISSUE TITLE
vmware fusion 8.0.0 support

### ISSUE THREAD

**Issue by rrva** [mitchellh/vagrant#6189]
After upgrading Fusion, I get:

This provider only works with VMware Fusion 5.x, 6.x, or 7.x. You have Fusion '8.0.0'. Please install the proper version of VMware Fusion and try again.

**Comment by rrva** [comment]
Search and replace 8.0.0 to 7.1.2 in the vmware-vmx binary works.

**Comment by sethvargo** [comment]
Hi @rrva,

Thank you for opening an issue. Our engineering team is working diligently to update the Vagrant VMware Fusion and Workstation plugins to support VMware Fusion 8 and VMware Workstation 12. Due to the number of API changes in the VMware software, this process may take some time.

We know this is an interruption to your workflow, and we are doing our best to add support as quickly as possible. If you have an immediate need to use Vagrant with VMware, please downgrade to VMware Fusion 7 or VMware Workstation 11. Sorry for the inconvenience.

Please watch the Vagrant mailing list for more information. We will post there when we have released the plugin as well as any applicable upgrade pricing.

Please let me know if you have any questions.

**Comment by benmartel** [comment]
@rrva how do you modify that file?

**Comment by mitchellh** [comment]
This is fixed and released. There were minimal API changes so we were able to do this quickly, we just took the time to run through tests. We're charging a standard upgrade fee as normal for new versions of VMware to continue to support development of our tooling.

**Comment by benmartel** [comment]
The update is not showing up. Any help?

**Comment by mitchellh** [comment]
We just upgraded across most of our company, it is version 4 of the plugin (which is uploaded). Vagrant itself doesn't need an update.

**Comment by TheBigBear** [comment]
I have paid and bought the upgrade of the plugin and installed the license and still get the same error message?

**Comment by TheBigBear** [comment]
OK, jsut found it, may I suggest you add this ```vagrant plugin update vagrant-vmware-fusion``` to the email sent out with the license purchase confirmation? Thanks.

**Comment by LeoNogueira** [comment]
I upgraded to El Capitan + VMWare Fusion 8 and also upgraded my VMWare Fusion plugin license.

After all the upgrade process I’m unable to vagrant up —provider=vmware_fusion. I receive the error:

You're using a license that doesn't allow you to use the installed
version of Fusion. This error message occurs if you upgraded Fusion
without also upgrading your license. Please upgrade your license to
unlock features and support for the latest version of VMware Fusion,
or revert your version of Fusion back to the supported version.
You can upgrade your license by going to the following URL:

http://license.hashicorp.com/upgrade/vmware2015

I issued vagrant vagrant plugin update vagrant-vmware-fusion but it didn’t worked.

Am I missing something ?

**Comment by TheBigBear** [comment]
What version of the plugin does it show?
