### ISSUE TITLE
Unable to set hostname with Ubuntu 15.10 box

### ISSUE THREAD

**Issue by F21** [mitchellh/vagrant#6577]
I am using the `ubuntu/wily64` box from here: https://atlas.hashicorp.com/ubuntu/boxes/wily64

In my vagrantfile, I have:
```
config.vm.hostname = "wily64-test"
```

After booting up, setting the hostname fails:
```
==> default: Setting hostname...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

service hostname start

Stdout from the command:



Stderr from the command:

mesg: ttyname failed: Inappropriate ioctl for device
Failed to start hostname.service: Unit hostname.service is masked.
```

Vagrant is 1.7.4 running on Windows 8.1 64-bit. VirtualBox is 5.0.10.

**Comment by sethvargo** [comment]
I think this should have been fixed by https://github.com/mitchellh/vagrant/pull/5937, but will do further testing to verify.

**Comment by sethvargo** [comment]
Just verified with that same box - setting the hostname works as expected! :smile:

**Comment by gabriel403** [comment]
@sethvargo  This still seems to be failing for me

```
==> dev: Setting hostname...
==> dev: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ip addr flush dev eth1 2> /dev/null

Stdout from the command:



Stderr from the command:

mesg: ttyname failed: Inappropriate ioctl for device


gabriel at Etruscan in ~/Projects/devbox on master [!]
$ vagrant -v
Vagrant 1.8.1
```

**Comment by JimMcHale** [comment]
I'm still seeing this issue today on 15.10 after doing an init with ubuntu/wily64
