### ISSUE TITLE
Vagrant tries to replace the insecure key AGAIN during vagrant halt - and fails

### ISSUE THREAD

**Issue by dhs-rec** [mitchellh/vagrant#7739]
Never seen this before, this is the first time. When I do a vagrant up of a newly created Ubuntu 16.04.1 box, I see output indicating the replacement of the vagrant insecure key:

```
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
==> default: Machine booted and ready!
```

Now, when I do vagrant halt, I get this:

```
==> default: Attempting graceful shutdown of VM...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

set -e

mkdir -p ~/.ssh
chmod 0700 ~/.ssh
cat '/tmp/vagrant-insert-pubkey-1471593000' >> ~/.ssh/authorized_keys
chmod 0600 ~/.ssh/authorized_keys

rm -f '/tmp/vagrant-insert-pubkey-1471593000'


Stdout from the command:



Stderr from the command:
```

And the box isn't halted. If I vagrant ssh into it, I see both the insecure and the new key in authorized_keys of the vagrant user.

The authorized_keys file has been initially set up using this shell snippet during packer build:

```
#!/usr/bin/env bash
set -e

su - vagrant -c bash <<EOF
mkdir --mode=0700 .ssh
dirs -c
pushd .ssh
echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key" >authorized_keys
chmod 0600 authorized_keys
popd
EOF
exit 0
```

### Vagrant version
Vagrant 1.8.5

### Host operating system
Windows Server 2012 R2

### Guest operating system
Ubuntu 16.04.1 LTS

### Vagrantfile
Pretty much default as created by vagrant init:
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "UbuntuTest"
end
```

### Debug output
https://gist.github.com/dhs-rec/0bf1bece1547ada2f459e109eb1eda67

### Expected behavior
vagrant halt should have halted the machine

### Actual behavior
See above

### Steps to reproduce
1. Create Ubuntu box with packer 
2. vagrant up that box
3. vagrant halt

**Comment by austenpayan** [comment]
Also experiencing this. Happens every time I vagrant halt, I have to rebuild the box every time. I'm sure theres a temporary workaround. 

Also on vagrant 1.8.5
on OSX 10.11.1

**Comment by dhs-rec** [comment]
Looking at the code, it seems like the rewritten **remove_public_key** method for Linux (commit: 4aaa600) doesn't work as expected.

**Comment by deviantintegral** [comment]
Also seeing this issue with Ubuntu 14.04 images.

**Comment by chrisroberts** [comment]
This should be resolved in 1.8.6. Can you confirm if you are still affected by this issue or if it is now resolved? Thanks!

**Comment by dhs-rec** [comment]
Looks better now. Thanks a lot.

**Comment by chrisroberts** [comment]
@dhs-rec great! Thanks for following up.

**Comment by dhs-rec** [comment]
Seems I was too fast (or testing with the wrong VM). In fact, the problem is still there.

**Comment by chrisroberts** [comment]
@dhs-rec can you provide me with version of vagrant you are using, your Vagrantfile, the version of the box you are using, and a gist of `vagrant halt --debug` showing the problem.

Thanks!

**Comment by dhs-rec** [comment]
Version: 1.8.6
Vagrantfile: See above
Gist of debug log: See above for 1.8.5; for 1.8.6 see https://gist.github.com/dhs-rec/814fcfea9c08f291d0344957346fb371

**Comment by nervo** [comment]
Same issue here.

I've noticed that none of the following commands https://github.com/mitchellh/vagrant/blob/master/plugins/guests/linux/cap/public_key.rb#L25 returns with a non-zero exit status, by adding some "echo $?" after each one.

I guess the issue is in the command handling itself. @chrisroberts any clues ?

**Comment by nervo** [comment]
Ah, i got it !

That's the "set -e". The commands (insert and remove) works when i remove it.
It was introduced by https://github.com/mitchellh/vagrant/commit/4aaa600bd6c677b5476ab47ed1cd1d8a04b35a95

Any ideas why ?

**Comment by chrisroberts** [comment]
Ah, perfect! @dhs-rec thanks for the debug log and @nervo thanks for actually having a look at it. A few `set -e`s were added that had an unexpected negative impact. I hadn't seen this one causing problems, but I see that it is indeed causing some issues. I'll get that cleaned up for this next release. 

Thanks to both of you!

**Comment by nervo** [comment]
@chrisroberts i've just found another useful information. In my own situation, the scripts crash because of zsh as shell. Switching to bash, and voila.
"set -e" is defintively not cross shell, maybe you can mimic its behavior by separating the commands with && ?

**Comment by UniIsland** [comment]
+1
upgraded to 1.8.6 and still experience this problem everytime I `vagrant halt`.
same with @nervo using zsh as shell in my box.
