### ISSUE TITLE
Vagrant up causes Blue Screen of Death after latest Windows 10 update

### ISSUE THREAD

**Issue by CallumBrankin** [mitchellh/vagrant#8791]
### Vagrant version
Vagrant 1.9.7

### Host operating system
Windows 10 Pro version 10.0.15063 Build 15063

### Guest operating system
Ubuntu

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "pixelpin/ubuntu-1604-lamp"
  config.vm.box_url = "file:///T:/pixelpin-ubuntu-1604-lamp.box"
# drupal7test.pixelpin.co.uk
  config.vm.network "private_network", ip: "192.168.33.12"
  
  

  config.vm.provision "shell", inline: <<-SHELL
  
	apt-get update
	apt-get install -y php7.0-zip
	service apache2 restart
  SHELL
end
```

### Expected behavior
Run Vagrant up, Virtual machine should be running

### Actual behavior
Blue Screen of death, after repairing disk it returns this error:

> There was an error while executing `VBoxManage`, a CLI used by Vagrant
> for controlling VirtualBox. The command and stderr is shown below.
> 
> Command: ["showvminfo", "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
> 0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"]
> 
> Stderr:

### Steps to reproduce
1. Update Windows 10 to latest version.
2. Open GitBash.
3. Run Vagrant Up.

After installing the lastest Windows 10 Creators update, whenever i run `vagrant up` i get a Blue Screen of Death. After running a disk scan and repair i get the error i stated above.

**Comment by CallumBrankin** [comment]
I've turned off Hyper-V in my BOIS, now it doesn't BSOD or show the previous error message. Now it just hangs on `SSH auth method: private key`

**Comment by CallumBrankin** [comment]
Fixed after turning off Hyper-V

**Comment by CallumBrankin** [comment]
It was a bug with either Hyper-V or VirtualBox

**Comment by Mnuzz** [comment]
Also happened to me, also fixed after turning off Hyper-V

**Comment by codifire** [comment]
I had the same issue and turning off Hyper-V fixed it, many thanks :)

**Comment by shellkjell** [comment]
BSOD so I turned Hyper-V off. Getting same \x00\x00.. error still though. Proceeded to turn VMware services off but still a no-go.

**Comment by foalthik** [comment]
for me not work turn off Hyper-V

**Comment by mtpultz** [comment]
Stepping back to Virtualbox 5.1.26 and turning of Hyper-V seems to work, but is super annoying since it means a restart now when switching over to using Docker.

**Comment by codifire** [comment]
@foalthik you might need to Enable VT-X from your BIOS

**Comment by taylankoca** [comment]
I'm having the same issue. I was using Vagrant 2.0.0, and there was no problem for one month. but starting from last thursday, I am having this problem.

**Comment by kervoaz** [comment]
I confirm also that HyperV deactivation fix the problem:
`bcdedit /set hypervisorlaunchtype off`
then reboot
vargrant up is working 
thnaks

**Comment by zigang93** [comment]
well... that why i hate window..

**Comment by mtpultz** [comment]
@zigang93 I subscribe to issues to talk about and be notified of solutions not to listen to peoples opinions on what OS they should or shouldn't be using.  If you don't have something helpful or constructive to add why are you adding a comment.  If you're not using Windows why are you even reading this issue or commenting?  If you are using Windows and just felt like commenting what have you contributed to the conversation?  Please keep your opinions to yourself outside of your own blog or appropriate online forums I don't want them in my inbox.

**Comment by mbehnke** [comment]
I confirm also that HyperV deactivation under Windows 10 Enterprise (1709, 16299.125) fix the "Bluescreen" Problem

**Comment by bhaskarv82** [comment]
I was using latest versions of vagrant and virtual box.
uninstalled vagrant and virtual box latest versions.
I downgraded these to
vagrant for windows 2.0.0
virtualbox 5.1.30
disabled Hyper-V settings on Windows 10
deleted directory .vagrant.d in my User/Home directory.
deleted all the files which were created with vagrant init or up
restarted windows.
worked fine.

Note: Our office work environment is pretty aggressive for security concerns but at home same setting works fine.

**Comment by mtttcgcg** [comment]
HyperV deactivation did not help me on Win 10 Enterprise (1709, 16299.125). After an uninstall and then reinstall of Vagrant, I still get the showvminfo error. 
Using the latest Vagrant downloaded today. Should we re-open this issue?

**Comment by sunel** [comment]
Same Issue: 

```bash
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["showvminfo", "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"]

Stderr:

```

**Comment by lgyaxx** [comment]
@kervoaz Thanks! Installed docker for windows today and vagrant up causes a blue screen. While docker needs to use hyperV, I need to turn if of to use vb again.

**Comment by SoucianceEqdamRashti** [comment]
I have turned off hyper-v and running latest vagrant and virtual box 5.2.6 and get a blue screen crash with vagrant up. Windows 10 professional edition.

**Comment by PhPPgAdminBug** [comment]
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["showvminfo", "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"]

set to solve 
1 - remove vagrant and never use it again with windows

**Comment by Boycce** [comment]
Why was this closed? Needing to restart to use docker is super annoying :/

**Comment by mtpultz** [comment]
Yah @Boycce, that is definitely annoying, but the issue of getting a blue screen of death has been fixed, and instead, it fails gracefully using a dialog based approach.  I don't remember exactly, but there is an issue with having Hyper-V on that can't be fixed..., but there is now a `hyper-v` provider that you can use.

**Comment by pixelicous** [comment]
@sunel - delete the .vagrant file
@boycce - this is how microsoft works, ask for logs, dont tackle the issue, return to github after 2 months, mass close issues without dealing with them


i haave the same issue, i see this dating back to 2016, a solution? you think?? :)

**Comment by pixelicous** [comment]
@sunel - delete the .vagrant file
@Boycce - this is how microsoft works, ask for logs, dont tackle the issue, return to github after 2 months, mass close issues without dealing with them
